### 17g installer config

## Distro section
distro_codename: endeavouros-next
distro_title: EndeavourOS
# distribution: auto
# copyright: 17g Developer Team

## Base options section
# loop_directory: /dev/loop0
log_file: /var/log/17g-installer.log
gtk_theme: Arc-Darker
welcome_screen: true
# exclude_dirs:
#   - /home

## Base system section
initramfs_system: auto 
using_shell: /bin/bash
# use_reboot: false
# remove_packages:
#   - 17g-installer

## User section
# list_users_when_auto_login: true
autologin_enabled: true
auto_partition_enabled: true
set_root_password: true
use_chpasswd: true
additional_user_groups:
   - wheel
   - sys
   - rfkill

## Partitioning section
# manual_partition_enabled: true 
# lvm_enabled: true
# encryption_enabled: true
# fill_disk_enabled: true
# set_alternative_ui: false
# partition_editor: gparted

## Timezone and locale section
# default_locale: auto
# default_timezone: America/New_York

## Setup page section
# skip_language: false
# skip_timezone: false
# skip_keyboard: false
# allow_uppercase_hostname: true
# allow_numeric_password: false
# min_password_length: 1

## Pre/Post operations section
post_install_commands:
   - /usr/bin/cleaner_script.sh
   - chroot || /usr/bin/chrooted_cleaner_script.sh
# pre_install_commands:
#   - cp /home/liveuser/mkinitcpio.conf /etc/mkinitcpio.conf
